### ISSUE TITLE
tf coordinator and test dataset problems 

### ISSUE THREAD

**Issue by bell-one** [Phog/DeepBlending#1]
Hello!

i'd like to test with your code,
and I follow all of the instruction you wrote.

but I cannot train with your code cause tf coordinator make some problems,

OS : ubuntu 16.04 LTS
CUDA : 10.0
TF : 1.15.0

I can learn with first batch, 
but when it goes to read next batch,

coordinator.join line make problems like below

```
Traceback (most recent call last):
  File "/home/bellone/Desktop/Deeplearning/deepblending/DeepBlending/train.py", line 587, in <module>
    coordinator.join(threads)
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/tensorflow_core/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/six.py", line 696, in reraise
Step: 0, batch loss: 91.420685
    raise value
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/tensorflow_core/python/training/queue_runner_impl.py", line 257, in _run
    enqueue_callable()
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1287, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Need minval < maxval, got 0 >= 0
	 [[{{node inputloader_1/random_uniform_4}}]]
  (1) Invalid argument: Need minval < maxval, got 0 >= 0
	 [[{{node inputloader_1/random_uniform_4}}]]
	 [[inputloader_1/concat/_1671]]
0 successful operations.
0 derived errors ignored.
```
I tried some answers with similar questions on google.
but I doesn't work well for me..

How can I solve this problem?

*And also, test dataset maybe broken.. 
lease check it
thank you

**Comment by bell-one** [comment]
And if i try with 
TF:1.10.0

```
  File "/home/bellone/Desktop/Deeplearning/deepblending/DeepBlending/train.py", line 587, in <module>
    coordinator.join(threads)
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/six.py", line 696, in reraise
    raise value
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1205, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/bellone/anaconda3/envs/deepblending/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= 0
	 [[Node: inputloader_1/random_uniform_4 = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:GPU:0"](inputloader_1/assert_greater_equal/Const, inputloader_1/random_uniform_4/min, inputloader_1/sub_1)]]
```

I can get similar error with coordinator

**Comment by bell-one** [comment]
Hello,

I solved this training problem with changing crop size argument 
default 256 to 128.

some of googles said this coordinator problem can be caused by memory size
My GPU was 1080ti 11GB.

**Comment by Phog** [comment]
That's great to hear! Thanks for responding with the solution to your problem.

Closing this issue as resolved.

**Comment by Phog** [comment]
P.S. 
All the models were trained with NVIDIA Titan X GPUs with at least 12 GB of memory.
